### ISSUE TITLE
Support PHP

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/polyglot-release#18]
### 🤔 What's the problem you're trying to solve?

Polyglot release should support all languages in the largest polyglot repo. Currently this is [cucumber-expressions](https://github.com/cucumber/cucumber-expressions) but will soon be Gherkin.

This includes PHP

**Comment by mpkorstanje** [comment]
Looks like PHP only uses git tags.

https://github.com/cucumber/common/blob/main/gherkin/php/default.mk#L29

**Comment by mattwynne** [comment]
I don't think there's anything to do here.

**Comment by mpkorstanje** [comment]
Then we should add it to the supported list.

**Comment by mattwynne** [comment]
Do you mean merging in #40 so it does an explicit noop? I wasn't sure why we needed that - will it error otherwise?

**Comment by mpkorstanje** [comment]
No it will not break, but it avoids confusion in the future. Because now we explicitly say that PHP should be a noop.

**Comment by mattwynne** [comment]
OK, so let's un-draft #40 and merge it?
