### ISSUE TITLE
Support monoglot-releases

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/polyglot-release#19]
### 🤔 What's the problem you're trying to solve?

Not all projects are polyglot such as [cucumber-react](https://github.com/cucumber/cucumber-react) but still benefit from the release automation.

### ✨ What's your proposed solution?

```
polyglot-release --monoglot-language=javascript
```

The ` --monoglot-language=javascript` would enable only the `javascript` language specific release parts. Would skip the `pushd/popd` commands.

It would also be nice if monoglot repos could be detected by looking at the existence of some well known file.

**Comment by mpkorstanje** [comment]
It would also be useful if monoglot repos could be detected automatically so the `--monoglot` flag wouldn't be needed.

**Comment by mattwynne** [comment]
I agree it would be great to be able to lean on this tool for a uniform way of doing releases, even in monglot repos.

In terms of the UI, and the underlying code, I'm wondering if we could break this thing up into separate commands (the way [adr-tools](https://github.com/npryce/adr-tools/tree/master/src) is structured) so we'd have e.g.

    polyglot-release javascript

We could add a switch for the source directory for now, then we can add auto-detection later, e.g.

    polyglot-release javascript --source-dir=.

**Comment by mpkorstanje** [comment]
I'm thinking we should make monoglot and polyglot first class citizens because those are our most common use cases.

So:

```
release polyglot v1.0.0   # Work out what, based on directory structure
release <language> v1.0.0 # Release the language, assume root.
```

Would be even better if we could infer `<language>` or `polyglot`. But the more we can infer from the project structure, the better.

**Comment by mpkorstanje** [comment]
This should help

https://temptemp3.github.io/bash-functions/
