### ISSUE TITLE
Print instructions of what to do next when using `--no-git-push`

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/polyglot-release#48]
### 🤔 What's the problem you're trying to solve?

When using `--no-git-push` there are some manual steps that need to be taken to finish the release. The steps are non-trivial so some help would be useful.

### ✨ What's your proposed solution?

Print instructions of what to do next when using `--no-git-push`. 

Instructions should include:

 * Commands to finish the release
 * Commands to roll back the release
 
 ### :stop_sign: What makes this difficult?
 
The `--no-git-commit` and `--only-release` get in the way. We could remove them with #49 .

**Comment by mattwynne** [comment]
I did #51 before I saw you'd raised this!

Doesn't include commands to roll back the release commits though, I didn't think of that.

I guess they could turn out not to be true if we don't remove the `--no-git-commit` and `--only-release` options. Good point.

**Comment by mattwynne** [comment]
Is this good enough for now @mpkorstanje? Can we trust that our users will know how to roll back the commits if they want to?
