### ISSUE TITLE
Remove  `--no-git-commit ` and  `--only-release`

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/polyglot-release#49]
### 🤔 What's the problem you've observed?

To solve #48 we have to take interactions with `--no-git-commit ` and  `--only-release` into account. This makes things really complicated.

### ✨ Do you have a proposal for making it better?

We introduced `--no-git-commit ` and  `--only-release` for testing because we didn't have a fancy git setup yet. Perhaps we can change the tests so we don't need these commands any more and instead check the patch files produced by git. I don't think there is a good usecase for these options because they leave the repo in a "strange state" that isn't really usable by anyone and requires a deep understanding of `polyglot-release` to roll back.

**Comment by mattwynne** [comment]
Agreed.

We could also use global variables, I guess, (like we do with the `RELEASE_DATE`) to let the tests tweak the behaviour but I don't like that option as much as modifying the test runner to inspect the git patches as you suggest.
