### ISSUE TITLE
--update is broken and corrupts the script

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/polyglot-release#76]
### 👓 What did you see?

This: (note my working directory is another project)

```
➜  language-service git:(main) POLYGLOT_RELEASE_VERSION=0.9.3
➜  language-service git:(main) curl --silent -o /usr/local/bin/polyglot-release https://raw.githubusercontent.com/cucumber/polyglot-release/v$POLYGLOT_RELEASE_VERSION/polyglot-release
➜  language-service git:(main) chmod 755 /usr/local/bin/polyglot-release
➜  language-service git:(main) polyglot-release --version
v0.9.3
➜  language-service git:(main) polyglot-release --update
Updated to v0.23.0
➜  language-service git:(main) polyglot-release --version
/usr/local/bin/polyglot-release: line 1: 404:: command not found
```

### ✅ What did you expect to see?

I expected `--update` to either say "you're on the latest version", or "Updated to v0.9.3". I also expected the script not to be corrupted.

**Comment by mpkorstanje** [comment]
This smells like you've got this in place:

https://github.com/cucumber/polyglot-release/pull/74/commits/20cbfd38df9b18de40af0e21e8d691564d5bf715#diff-6bfe0b1d529f955a9c9cd8beb8e5515160dd63befa1ad8b04858ef449ace6d84R346

**Comment by mpkorstanje** [comment]
Could you cat `/usr/local/bin/polyglot-releas` then? See what is there?

**Comment by aslakhellesoy** [comment]
Indeed - I had a leftover `POLYGLOT_RELEASE_GIT_REPO` defined in my shell. Undefining it makes the problem go away. Sorry for the false alarm.
