### ISSUE TITLE
The 0.9.3 release is bricked

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/polyglot-release#77]
### 👓 What did you see?

Trying to release `@cucumber/language-service 0.23.1` I saw this:

```
➜  language-service git:(main) polyglot-release 0.23.1
Please run polyglot-release --update
 - current version: v0.9.3
 - latest version: v0.23.0
``` 

### ✅ What did you expect to see?

🌈🦄

### 📦 Which tool/library version are you using?

polyglot-release 0.9.3

**Comment by mpkorstanje** [comment]
>  - latest version: v0.23.0

This smells like you've still got this in place:

https://github.com/cucumber/polyglot-release/pull/74/commits/20cbfd38df9b18de40af0e21e8d691564d5bf715#diff-6bfe0b1d529f955a9c9cd8beb8e5515160dd63befa1ad8b04858ef449ace6d84R346

**Comment by aslakhellesoy** [comment]
Indeed - I had a leftover `POLYGLOT_RELEASE_GIT_REPO` defined in my shell. Undefining it makes the problem go away. Sorry for the false alarm.
