### ISSUE TITLE
Tests are brittle to current date

### ISSUE THREAD

**Issue by mattwynne** [cucumber/polyglot-release#8]
### 🤔 What's the problem you've observed?

Test data for comparison with actual output contains "today's date" for the "1.0.0" release.

See https://github.com/cucumber/polyglot-release/runs/5878121439?check_suite_focus=true

### ✨ Do you have a proposal for making it better?

Options I can see:

* normalise the output before comparison, doing some kind of date substitution
* allow a `--release-date=<date>` option that we can use to inject the date in tests (we can pass this to `changelog`; it supports it.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
Lol, gotta sed those out then or normalize them.
