### ISSUE TITLE
More extensible tests?

### ISSUE THREAD

**Issue by mattwynne** [cucumber/polyglot-release#9]
### 🤔 What's the problem you've observed?

We're adding tests in the same file.

### ✨ Do you have a proposal for making it better?

Could draw inspiration from https://github.com/tooky/retro-tools and loop over separate test scripts in a directory.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
I'd wait until we have 10 tests. Ideally we'd also create a new temp folder with git repo for each test. But that was a bit too much for something so simple.
